Add .net framework versions 4.7, 4.7.1 and 4.7.2 as available TargetFrameworkVersion values
rsdn/nemerle pull request #13345
Opened 2018-06-23 11:26 UTC by NilFusion

Add .net framework versions 4.7, 4.7.1 and 4.7.2 as available TargetFrameworkVersion values

2019-04-20 10:11 UTC, NN--- commented
I think that editorconfig is unrelated to this commit.

2019-04-20 14:19 UTC, NilFusion commented
Yeah, github is wiered. I did not intend to include it into this PR, only push to my fork. If you know, how to fix it, please, tell me. Anyway, it's good i didn't push anything really significant.
btw, are you interested in vs2019 support (some apis got obsolete and were removed, some are not working properly), new msbuild sdk support or code highliting like in vs2017/2019 for c#? We're working on it, but it may take time.
Sorry to say that, we may be wrong, but we got an impression this project was abandoned
/
З.Ы. Официальный английский мне, видимо, даётся плохо. Я не так давно проникся идеей немерле, но обидно видеть, что в последнее время он не получает должной поддержки. За помощь с разруливанием попадания лишнего коммита в пул-реквест буду благодарен

2019-04-20 18:43 UTC, NN--- commented
Да проект интересный и вполне может использоваться для обущающих целей.

По всем вопросам можно обращаться на форум https://rsdn.org/forum/nemerle.
К сожалению проект остался не у дел.

Дальнейшие наработки идут здесь: https://github.com/rsdn/nitra

2019-04-20 18:44 UTC, NN--- commented
Кстати а вышедший только что 4.8 не стоит ли добавить ?

2019-04-20 19:54 UTC, NilFusion commented
Добавил 4.8 и дефолтный для 2019 студии на будущее + гитигнор
спасибо, обращусь на форум
з.ы. то чувство, когда мэйнтейнер считает проект подходящим для обучающих целей, а вы его в продакшне используете

2019-04-20 20:04 UTC, NN--- requested changes

2019-04-20 20:04 UTC, NN--- commented on snippets/VS2010/Nemerle.VisualStudio/Project/NetFrameworkProjectConstants.cs
> +    private const string FrameworkVersion472 = "4.8";
FrameworkVersion48

2019-04-20 20:06 UTC, NilFusion commented on snippets/VS2010/Nemerle.VisualStudio/Project/NetFrameworkProjectConstants.cs
> +    private const string FrameworkVersion472 = "4.8";
fixed in latest commit

2019-04-20 20:14 UTC, merged

2019-04-23 09:31 UTC, kskalski commented
> btw, are you interested in vs2019 support (some apis got obsolete and were removed, some are not working properly), new msbuild sdk support or code highliting like in vs2017/2019 for c#?

It would be great to get the support for vs2019 :-)

2019-04-23 18:09 UTC, NilFusion commented
@kskalski Here you go: [VS 2019 Extension](/NilFusion/nemerle/tree/vs2019.legacyApis). For now you have to build it by yourself. Instruction is provieded in the description.
I won't make PR for this, until backward compatibility build issues are resolved, and them are not a priority now. Maybe this issues are related only to VS2019, which i have installed without any other VS versions.